--MS SQL SERVER Script


CREATE DATABASE DataHaus_Brewery;

USE DataHaus_Brewery;

CREATE SCHEMA BrewHaus AUTHORIZATION dbo 


CREATE TABLE DataHaus_Brewery.BrewHaus.BREWERY (
  BREWERY_ID INT NOT NULL,
  BREWERY_NAME VARCHAR(50) NOT NULL,
  BREWERY_ADDRESS VARCHAR(100),
  BREWREY_CITY VARCHAR(50),
  BREWERY_STATE VARCHAR(2),
  BREWERY_ZIP VARCHAR(5),
  BREWERY_PHONE VARCHAR(10),
  BREWERY_EMAIL VARCHAR(50),
  BREWERY_WEBSITE VARCHAR(100),
  CONSTRAINT PK_BREWERY_BREWERY_ID PRIMARY KEY CLUSTERED (BREWERY_ID)
);
CREATE TABLE DataHaus_Brewery.BrewHaus.TAPROOM (
  TAPROOM_ID INT NOT NULL,
  BREWERY_ID INT,
  TAPROOM_NAME VARCHAR(50) NOT NULL,
  TAPROOM_ADDRESS VARCHAR(100),
  TAPROOM_CITY VARCHAR(50),
  TAPROOM_ZIP VARCHAR(5),
  TAPROOM_PHONE VARCHAR(10),
  TAPROOM_EMAIL VARCHAR(50),
  TAPROOM_WEBSITE VARCHAR(100),
  LICENSE_NUMBER INT,
  CONSTRAINT PK_TAPROOM_TAPROOM_ID PRIMARY KEY CLUSTERED (TAPROOM_ID),
  CONSTRAINT FK_TAPROOM_BREWERY_ID FOREIGN KEY (BREWERY_ID) REFERENECES DataHaus_BrewBase.BrewBase.BREWERY (BREWERY_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE DataHaus_Brewery.BrewHaus.STYLE (
  STYLE_ID INT NOT NULL,
  STYLE_NAME VARCHAR(50),
  STYLE_ORIGIN VARCHAR(30),
  STYLE_GLASS_TYPE VARCHAR(30),
  STYLE_DESCTIPTION VARCHAR(300),
  CONSTRAINT PK_STYLE_STYLE_ID PRIMARY KEY CLUSTERED (STYLE_ID)
);
CREATE TABLE DataHaus_Brewery.BrewHaus.BEER (
  BEER_UPC INT NOT NULL,
  BREWERY_ID INT NOT NULL,
  STYLE_ID INT NOT NULL,
  BEER_NAME VARCHAR(30) NOT NULL,
  BEER_IBU INT,
  BEER_ABV DECIMAL(19,2),
  BEER_YEAR VARCHAR(4),
  OZ_AVAILABLE INT,
  BEER_COST DECIMAL(19,2),
  BEER_DESCRIPTION VARCHAR(300),
  CONSTRAINT PK_BEER_BEER_UPC PRIMARY KEY CLUSTERED (BEER_UPC),
  CONSTRAINT FK_BEER_BREWERY_ID FOREIGN KEY (BREWERY_ID) REFERENCES DataHaus_Brewery.BrewHaus.BREWERY (BREWERY_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_STYLE_STYLE_ID FOREIGN KEY (STYLE_ID) REFERENCES DataHaus_Brewery.BrewHaus.STYLE (STYLE_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE DataHaus_Brewery.BrewHaus.PURCHASE (
  PURCHASE_ID INT NOT NULL,
  TAPROOM_ID INT NOT NULL,
  PURCHASE_DATE DATE,
  CONSTRAINT PK_PURCHASE_PURCHASE_ID PRIMARY KEY CLUSTERED (PURCHASE_ID),
  CONSTRAINT FK_PURCHASE_TAPROOM_ID FOREIGN KEY (TAPROOM_ID) REFERENCES DataHaus_Brewery.BrewHaus.TAPROOM (TAPROOM_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE DataHaus_Brewery.BrewHaus.PURCHASE_ITEMS (
  PURCHASE_ID INT NOT NULL,
  PURCHASE_ITEMS_ID INT NOT NULL,
  BEER_UPC INT NOT NULL,
  PRUCHASE_ITEM_QTY INT,
  PURCHASE_ITEM_PRICE DECIMAL(19,2),
  CONSTRAINT PK_PURCHASE_ITEMS PRIMARY KEY (PURCHASE_ID, PURCHASE_ITEMS_ID),
  CONSTRAINT FK_PURCHASE_ITEMS_PURHCASE_ID FOREIGN KEY (PURCHASE_ID) REFERENCES DataHaus_Brewery.BrewHaus.PURCHASE (PURCHASE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_PURCHASE_ITEMS_BEER_UPC FOREIGN KEY (BEER_UPC) REFERENCES DataHaus_Brewery.BrewHaus.BEER (BEER_UPC) ON DELETE NO ACTION ON UPDATE NO ACTION
);

